QE-4 e2e | Registration
andrewnovykov/realworld-qe pull request #2
Opened 2023-02-09 05:24 UTC by qafromla

https://qafromla.atlassian.net/browse/QE-4 
This PR includes : 
1. new test QALA-2 
2. new test QALA-6

2023-02-09 05:51 UTC, papapin requested changes

2023-02-09 05:51 UTC, papapin commented on cypress/e2e/registration.cy.js
> +		homePage.visit()
use real credentials

2023-02-09 05:51 UTC, papapin commented on cypress/pages/home.page.js
>  		cy.visit('https://qafromla.herokuapp.com/')
move to Base Url

2023-02-13 02:35 UTC, qafromla commented on cypress/e2e/registration.cy.js
> +		homePage.visit()
done

2023-02-13 02:55 UTC, papapin approved these changes
LGTM!

2023-02-13 02:55 UTC, merged